name: Test Secrets Configuration

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug mode'
        required: false
        default: 'false'
        type: boolean

jobs:
  test-secrets:
    name: Verify GitHub Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check Cloudflare secrets
        run: |
          echo "::notice::Testing Cloudflare secrets configuration..."
          
          # Check if secrets exist (values are masked)
          if [[ -n "$CLOUDFLARE_ACCOUNT_ID" ]]; then
            echo "✅ CLOUDFLARE_ACCOUNT_ID is configured (length: ${#CLOUDFLARE_ACCOUNT_ID})"
          else
            echo "❌ CLOUDFLARE_ACCOUNT_ID is NOT configured"
            exit 1
          fi
          
          if [[ -n "$CLOUDFLARE_API_TOKEN" ]]; then
            echo "✅ CLOUDFLARE_API_TOKEN is configured (length: ${#CLOUDFLARE_API_TOKEN})"
          else
            echo "❌ CLOUDFLARE_API_TOKEN is NOT configured"
            exit 1
          fi
          
          # Expected account ID length is 32 characters
          if [[ ${#CLOUDFLARE_ACCOUNT_ID} -eq 32 ]]; then
            echo "✅ CLOUDFLARE_ACCOUNT_ID has correct length"
          else
            echo "⚠️  CLOUDFLARE_ACCOUNT_ID length unexpected: ${#CLOUDFLARE_ACCOUNT_ID} (expected: 32)"
          fi
          
          echo "::notice::All required secrets appear to be configured!"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      
      - name: Check optional GCP secret
        run: |
          if [[ -n "$GCP_SERVICE_ACCOUNT_KEY" ]]; then
            echo "✅ GCP_SERVICE_ACCOUNT_KEY is configured (optional)"
            # Try to parse as JSON
            echo "$GCP_SERVICE_ACCOUNT_KEY" | jq empty 2>/dev/null && echo "✅ Valid JSON format" || echo "⚠️  Invalid JSON format"
          else
            echo "ℹ️  GCP_SERVICE_ACCOUNT_KEY is not configured (optional)"
          fi
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        continue-on-error: true
      
      - name: Test Wrangler authentication
        if: ${{ github.event.inputs.debug_mode == 'true' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: whoami
      
      - name: Summary
        run: |
          echo "## Secret Configuration Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Secret | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| CLOUDFLARE_ACCOUNT_ID | $([[ -n "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]] && echo "✅ Configured" || echo "❌ Missing") |" >> $GITHUB_STEP_SUMMARY
          echo "| CLOUDFLARE_API_TOKEN | $([[ -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]] && echo "✅ Configured" || echo "❌ Missing") |" >> $GITHUB_STEP_SUMMARY
          echo "| GCP_SERVICE_ACCOUNT_KEY | $([[ -n "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" ]] && echo "✅ Configured" || echo "ℹ️ Not set (optional)") |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Run this workflow with debug mode enabled to test Wrangler authentication." >> $GITHUB_STEP_SUMMARY